# Generated by Django 2.0.5 on 2018-06-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_enabled', models.BooleanField(default=True)),
                ('catalog_url', models.CharField(default='#', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reply_to', models.PositiveIntegerField(blank=True, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('lock', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('top', models.BooleanField(default=False)),
                ('top_time', models.DateTimeField(null=True)),
                ('like_count', models.PositiveIntegerField(default=1)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('img_link', models.TextField(blank=True, null=True)),
                ('catalog', models.ForeignKey(on_delete='cascade', related_name='posts', to='hh.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(error_messages={'unique': '用户名已存在'}, max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(error_messages={'unique': '邮箱已存在'}, max_length=254, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
                ('head_picture', models.TextField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.ForeignKey(on_delete='cascade', related_name='posts', to='hh.Users'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete='cascade', related_name='likes', to='hh.Post'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete='cascade', related_name='likes', to='hh.Users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete='cascade', related_name='comments', to='hh.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete='cascade', related_name='comments', to='hh.Users'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
